<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="MAIN" Id="{5389bffc-5fc7-4629-b6a9-ec8909c13e1e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Value1 : INT;
	Value2 : INT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>